import json
import subprocess
import tempfile
import unittest
from pathlib import Path


class BuildMetadataGenerationTests(unittest.TestCase):
    def setUp(self) -> None:
        self.project = Path(__file__).parents[1]
        self.script = self.project / "scripts/generate_build_metadata.py"

    def test_official_source_fields_generate_swift_runtime_constants(self) -> None:
        fixture = {
            "desktopVersion": '99.1"preview',
            "desktopBuild": "6000",
            "embeddedCliVersion": "1.2\\beta\nnext",
            "sourceCommit": "0123456789abcdef0123456789abcdef01234567",
        }
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            source = root / "official-source.json"
            output = root / "Domain" / "CodexBuildMetadata.generated.swift"
            source.write_text(json.dumps(fixture), encoding="utf-8")

            subprocess.run(
                [
                    "python3",
                    str(self.script),
                    "--source",
                    str(source),
                    "--swift-output",
                    str(output),
                ],
                check=True,
            )

            generated = output.read_text(encoding="utf-8")
            self.assertIn("public enum CodexBuildMetadata", generated)
            self.assertIn(
                'public static let desktopVersion = "99.1\\"preview"',
                generated,
            )
            self.assertIn(
                'public static let desktopBuild = "6000"',
                generated,
            )
            self.assertIn(
                'public static let embeddedCliVersion = "1.2\\\\beta\\nnext"',
                generated,
            )
            self.assertIn(
                'public static let sourceCommit = '
                '"0123456789abcdef0123456789abcdef01234567"',
                generated,
            )
            self.assertIn(
                "Regenerated by scripts/generate_build_metadata.py",
                generated,
            )

    def test_missing_official_field_is_rejected_without_replacing_output(
        self,
    ) -> None:
        fixture = {
            "desktopVersion": "99.1",
            "desktopBuild": "6000",
            "embeddedCliVersion": "1.2.3",
        }
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            source = root / "official-source.json"
            output = root / "CodexBuildMetadata.generated.swift"
            source.write_text(json.dumps(fixture), encoding="utf-8")
            output.write_text("previous generated metadata\n", encoding="utf-8")

            result = subprocess.run(
                [
                    "python3",
                    str(self.script),
                    "--source",
                    str(source),
                    "--swift-output",
                    str(output),
                ],
                capture_output=True,
                text=True,
            )

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("sourceCommit", result.stderr)
            self.assertEqual(
                output.read_text(encoding="utf-8"),
                "previous generated metadata\n",
            )

    def test_repository_metadata_is_generated_from_current_official_record(
        self,
    ) -> None:
        source = (
            self.project
            / "versions/26.721.81911/official-source.json"
        )
        if not source.is_file():
            self.skipTest(
                "official source records are not distributed in the public "
                "source repository"
            )
        expected = json.loads(source.read_text(encoding="utf-8"))
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "CodexBuildMetadata.generated.swift"

            subprocess.run(
                [
                    "python3",
                    str(self.script),
                    "--source",
                    str(source),
                    "--swift-output",
                    str(output),
                ],
                check=True,
            )

            generated = output.read_text(encoding="utf-8")
            for field in (
                "desktopVersion",
                "desktopBuild",
                "embeddedCliVersion",
                "sourceCommit",
            ):
                self.assertIn(
                    f'public static let {field} = "{expected[field]}"',
                    generated,
                )


if __name__ == "__main__":
    unittest.main()
