// Generated from the imported official source provenance record.
// Regenerated by scripts/generate_build_metadata.py during every upgrade.
public enum CodexBuildMetadata {
    public static let desktopVersion = "26.814.41957"
    public static let desktopBuild = "6744"
    public static let embeddedCliVersion = "0.148.0-alpha.15"
    public static let sourceCommit = "ffe1de5cec9c0cd02629eb246534e4622da0ff41"
}
