// Generated from the complete official Codex model catalog for desktop build 26.820.60940.
// Runtime model selection uses model/list; this is a versioned fallback snapshot.
// Regenerated by scripts/generate_model_catalog.py during every upgrade.
extension CodexModelCatalog {
    public static let current: [CodexModelConfiguration] = [
        .init(
            id: "gpt-5.6-sol",
            model: "gpt-5.6-sol",
            upgrade: nil,
            upgradeInfo: nil,
            availabilityNux: nil,
            displayName: "GPT-5.6-Sol",
            description: "Latest frontier agentic coding model.",
            hidden: false,
            reasoningEffortOptions: [
                .init(reasoningEffort: .low, description: "Fast responses with lighter reasoning"),
                .init(reasoningEffort: .medium, description: "Balances speed and reasoning depth for everyday tasks"),
                .init(reasoningEffort: .high, description: "Greater reasoning depth for complex problems"),
                .init(reasoningEffort: .xhigh, description: "Extra high reasoning depth for complex problems"),
                .init(reasoningEffort: .max, description: "Maximum reasoning depth for the hardest problems"),
                .init(reasoningEffort: .ultra, description: "Maximum reasoning with automatic task delegation"),
            ],
            defaultReasoningEffort: .low,
            inputModalities: [.text, .image],
            supportsPersonality: false,
            additionalSpeedTiers: ["fast"],
            serviceTiers: [
                .init(id: "priority", name: "Fast", description: "1.5x speed, increased usage"),
            ],
            defaultServiceTier: nil,
            isDefault: true
        ),
        .init(
            id: "gpt-5.6-terra",
            model: "gpt-5.6-terra",
            upgrade: nil,
            upgradeInfo: nil,
            availabilityNux: nil,
            displayName: "GPT-5.6-Terra",
            description: "Balanced agentic coding model for everyday work.",
            hidden: false,
            reasoningEffortOptions: [
                .init(reasoningEffort: .low, description: "Fast responses with lighter reasoning"),
                .init(reasoningEffort: .medium, description: "Balances speed and reasoning depth for everyday tasks"),
                .init(reasoningEffort: .high, description: "Greater reasoning depth for complex problems"),
                .init(reasoningEffort: .xhigh, description: "Extra high reasoning depth for complex problems"),
                .init(reasoningEffort: .max, description: "Maximum reasoning depth for the hardest problems"),
                .init(reasoningEffort: .ultra, description: "Maximum reasoning with automatic task delegation"),
            ],
            defaultReasoningEffort: .medium,
            inputModalities: [.text, .image],
            supportsPersonality: false,
            additionalSpeedTiers: ["fast"],
            serviceTiers: [
                .init(id: "priority", name: "Fast", description: "1.5x speed, increased usage"),
            ],
            defaultServiceTier: nil,
            isDefault: false
        ),
        .init(
            id: "gpt-5.6-luna",
            model: "gpt-5.6-luna",
            upgrade: nil,
            upgradeInfo: nil,
            availabilityNux: nil,
            displayName: "GPT-5.6-Luna",
            description: "Fast and affordable agentic coding model.",
            hidden: false,
            reasoningEffortOptions: [
                .init(reasoningEffort: .low, description: "Fast responses with lighter reasoning"),
                .init(reasoningEffort: .medium, description: "Balances speed and reasoning depth for everyday tasks"),
                .init(reasoningEffort: .high, description: "Greater reasoning depth for complex problems"),
                .init(reasoningEffort: .xhigh, description: "Extra high reasoning depth for complex problems"),
                .init(reasoningEffort: .max, description: "Maximum reasoning depth for the hardest problems"),
            ],
            defaultReasoningEffort: .medium,
            inputModalities: [.text, .image],
            supportsPersonality: false,
            additionalSpeedTiers: ["fast"],
            serviceTiers: [
                .init(id: "priority", name: "Fast", description: "1.5x speed, increased usage"),
            ],
            defaultServiceTier: nil,
            isDefault: false
        ),
        .init(
            id: "gpt-5.5",
            model: "gpt-5.5",
            upgrade: nil,
            upgradeInfo: nil,
            availabilityNux: nil,
            displayName: "GPT-5.5",
            description: "Frontier model for complex coding, research, and real-world work.",
            hidden: false,
            reasoningEffortOptions: [
                .init(reasoningEffort: .low, description: "Fast responses with lighter reasoning"),
                .init(reasoningEffort: .medium, description: "Balances speed and reasoning depth for everyday tasks"),
                .init(reasoningEffort: .high, description: "Greater reasoning depth for complex problems"),
                .init(reasoningEffort: .xhigh, description: "Extra high reasoning depth for complex problems"),
            ],
            defaultReasoningEffort: .medium,
            inputModalities: [.text, .image],
            supportsPersonality: true,
            additionalSpeedTiers: ["fast"],
            serviceTiers: [
                .init(id: "priority", name: "Fast", description: "1.5x speed, increased usage"),
            ],
            defaultServiceTier: nil,
            isDefault: false
        ),
        .init(
            id: "gpt-5.4",
            model: "gpt-5.4",
            upgrade: "gpt-5.6-terra",
            upgradeInfo: .init(
                model: "gpt-5.6-terra",
                upgradeCopy: nil,
                modelLink: nil,
                migrationMarkdown: "GPT-5.4 will be deprecated soon\n\nCodex now uses GPT-5.6 Terra in place of GPT-5.4. Switch to GPT-5.6 Terra to continue.\n"
            ),
            availabilityNux: nil,
            displayName: "GPT-5.4",
            description: "Strong model for everyday coding.",
            hidden: false,
            reasoningEffortOptions: [
                .init(reasoningEffort: .low, description: "Fast responses with lighter reasoning"),
                .init(reasoningEffort: .medium, description: "Balances speed and reasoning depth for everyday tasks"),
                .init(reasoningEffort: .high, description: "Greater reasoning depth for complex problems"),
                .init(reasoningEffort: .xhigh, description: "Extra high reasoning depth for complex problems"),
            ],
            defaultReasoningEffort: .medium,
            inputModalities: [.text, .image],
            supportsPersonality: true,
            additionalSpeedTiers: ["fast"],
            serviceTiers: [
                .init(id: "priority", name: "Fast", description: "1.5x speed, increased usage"),
            ],
            defaultServiceTier: nil,
            isDefault: false
        ),
        .init(
            id: "gpt-5.4-mini",
            model: "gpt-5.4-mini",
            upgrade: "gpt-5.6-luna",
            upgradeInfo: .init(
                model: "gpt-5.6-luna",
                upgradeCopy: nil,
                modelLink: nil,
                migrationMarkdown: "GPT-5.4 Mini will be deprecated soon\n\nCodex now uses GPT-5.6 Luna in place of GPT-5.4 Mini. Switch to GPT-5.6 Luna to continue.\n"
            ),
            availabilityNux: nil,
            displayName: "GPT-5.4-Mini",
            description: "Small, fast, and cost-efficient model for simpler coding tasks.",
            hidden: false,
            reasoningEffortOptions: [
                .init(reasoningEffort: .low, description: "Fast responses with lighter reasoning"),
                .init(reasoningEffort: .medium, description: "Balances speed and reasoning depth for everyday tasks"),
                .init(reasoningEffort: .high, description: "Greater reasoning depth for complex problems"),
                .init(reasoningEffort: .xhigh, description: "Extra high reasoning depth for complex problems"),
            ],
            defaultReasoningEffort: .medium,
            inputModalities: [.text, .image],
            supportsPersonality: true,
            additionalSpeedTiers: [],
            serviceTiers: [],
            defaultServiceTier: nil,
            isDefault: false
        ),
        .init(
            id: "gpt-5.3-codex-spark",
            model: "gpt-5.3-codex-spark",
            upgrade: nil,
            upgradeInfo: nil,
            availabilityNux: nil,
            displayName: "GPT-5.3-Codex-Spark",
            description: "Ultra-fast coding model.",
            hidden: false,
            reasoningEffortOptions: [
                .init(reasoningEffort: .low, description: "Fast responses with lighter reasoning"),
                .init(reasoningEffort: .medium, description: "Balances speed and reasoning depth for everyday tasks"),
                .init(reasoningEffort: .high, description: "Greater reasoning depth for complex problems"),
                .init(reasoningEffort: .xhigh, description: "Extra high reasoning depth for complex problems"),
            ],
            defaultReasoningEffort: .high,
            inputModalities: [.text],
            supportsPersonality: true,
            additionalSpeedTiers: [],
            serviceTiers: [],
            defaultServiceTier: nil,
            isDefault: false
        )
    ]
}
