#!/usr/bin/env python3
"""Generate runtime build constants from an official source provenance record."""

from __future__ import annotations

import argparse
import json
import os
import tempfile
from pathlib import Path


REQUIRED_STRING_FIELDS = (
    "desktopVersion",
    "desktopBuild",
    "embeddedCliVersion",
    "sourceCommit",
)


def _load_metadata(source: Path) -> dict[str, str]:
    document = json.loads(source.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ValueError("official source record must be a JSON object")

    metadata: dict[str, str] = {}
    for field in REQUIRED_STRING_FIELDS:
        value = document.get(field)
        if not isinstance(value, str) or not value:
            raise ValueError(
                f"official source field {field} must be a non-empty string"
            )
        try:
            value.encode("utf-8")
        except UnicodeEncodeError as error:
            raise ValueError(
                f"official source field {field} contains invalid Unicode"
            ) from error
        metadata[field] = value
    return metadata


def _swift_string(value: str) -> str:
    escaped: list[str] = []
    for character in value:
        codepoint = ord(character)
        if character == "\\":
            escaped.append("\\\\")
        elif character == '"':
            escaped.append('\\"')
        elif character == "\n":
            escaped.append("\\n")
        elif character == "\r":
            escaped.append("\\r")
        elif character == "\t":
            escaped.append("\\t")
        elif (
            codepoint < 0x20
            or codepoint == 0x7F
            or codepoint in (0x2028, 0x2029)
        ):
            escaped.append(f"\\u{{{codepoint:X}}}")
        else:
            escaped.append(character)
    return '"' + "".join(escaped) + '"'


def _render_swift(metadata: dict[str, str]) -> str:
    return """\
// Generated from the imported official source provenance record.
// Regenerated by scripts/generate_build_metadata.py during every upgrade.
public enum CodexBuildMetadata {
    public static let desktopVersion = %s
    public static let desktopBuild = %s
    public static let embeddedCliVersion = %s
    public static let sourceCommit = %s
}
""" % tuple(
        _swift_string(metadata[field]) for field in REQUIRED_STRING_FIELDS
    )


def _write_atomic(output: Path, content: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=output.parent,
            prefix=f".{output.name}.",
            delete=False,
        ) as temporary:
            temporary.write(content)
            temporary_path = Path(temporary.name)
        os.chmod(temporary_path, 0o644)
        os.replace(temporary_path, output)
    finally:
        if temporary_path is not None and temporary_path.exists():
            temporary_path.unlink()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--swift-output", type=Path, required=True)
    args = parser.parse_args()

    try:
        metadata = _load_metadata(args.source)
        generated = _render_swift(metadata)
        _write_atomic(args.swift_output, generated)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        parser.error(str(error))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
