#!/usr/bin/env python3
"""Generate the iPad feature catalog from the exact reversed Codex Rust registry."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def feature_blocks(source: str) -> list[str]:
    marker = "pub const FEATURES:"
    start = source.index(marker)
    start = source.index("[", start) + 1
    end = source.index("\n];", start)
    blocks: list[str] = []
    cursor = start
    while True:
        match = re.search(r"\bFeatureSpec\s*\{", source[cursor:end])
        if match is None:
            break
        block_start = cursor + match.start()
        brace_start = cursor + match.end() - 1
        depth = 0
        in_string = False
        escaped = False
        for index in range(brace_start, end):
            char = source[index]
            if in_string:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == '"':
                    in_string = False
                continue
            if char == '"':
                in_string = True
            elif char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    blocks.append(source[block_start : index + 1])
                    cursor = index + 1
                    break
        else:
            raise ValueError("unterminated FeatureSpec")
    return blocks


def string_field(block: str, name: str) -> str | None:
    match = re.search(
        rf"\b{name}\s*:\s*\"((?:\\.|[^\"\\])*)\"", block, re.DOTALL
    )
    if match is None:
        return None
    return bytes(match.group(1), "utf-8").decode("unicode_escape")


def swift_string(value: str | None) -> str:
    if value is None:
        return "nil"
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def parse_feature(block: str) -> dict[str, object]:
    key = string_field(block, "key")
    if key is None:
        raise ValueError(f"FeatureSpec missing key: {block[:80]}")
    default_match = re.search(
        r"\bdefault_enabled\s*:\s*([^,\n]+)", block
    )
    if default_match is None:
        raise ValueError(f"FeatureSpec {key} missing default_enabled")
    default_expression = default_match.group(1).strip()
    # The generated catalog targets iPadOS, so cfg!(windows) is false.
    default_enabled = {
        "true": True,
        "false": False,
        "cfg!(windows)": False,
        "!cfg!(windows)": True,
    }.get(default_expression)
    if default_enabled is None:
        raise ValueError(
            f"unsupported default expression for {key}: {default_expression}"
        )

    if "Stage::Experimental" in block:
        stage = "beta"
        display_name = string_field(block, "name")
        description = string_field(block, "menu_description")
        announcement = string_field(block, "announcement")
        if announcement == "":
            announcement = None
    else:
        stage_match = re.search(
            r"\bstage\s*:\s*Stage::"
            r"(UnderDevelopment|Stable|Deprecated|Removed)",
            block,
        )
        if stage_match is None:
            raise ValueError(f"unsupported stage for {key}")
        stage = {
            "UnderDevelopment": "underDevelopment",
            "Stable": "stable",
            "Deprecated": "deprecated",
            "Removed": "removed",
        }[stage_match.group(1)]
        display_name = description = announcement = None

    return {
        "name": key,
        "stage": stage,
        "display_name": display_name,
        "description": description,
        "announcement": announcement,
        "default_enabled": default_enabled,
    }


def render(features: list[dict[str, object]], source_path: Path) -> str:
    lines = [
        "// Generated by scripts/generate_experimental_feature_catalog.py.",
        f"// Source: {source_path.as_posix()}",
        "// Do not edit this file by hand.",
        "",
        "extension CodexExperimentalFeatureSpec {",
        "    public static let releasedCatalog: [Self] = [",
    ]
    for feature in features:
        lines.extend(
            [
                "        .init(",
                f'            name: {swift_string(feature["name"])},',
                f'            stage: .{feature["stage"]},',
                "            displayName: "
                f'{swift_string(feature["display_name"])},',
                "            description: "
                f'{swift_string(feature["description"])},',
                "            announcement: "
                f'{swift_string(feature["announcement"])},',
                "            defaultEnabled: "
                f'{"true" if feature["default_enabled"] else "false"}',
                "        ),",
            ]
        )
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--expected-count", type=int)
    args = parser.parse_args()

    features = [
        parse_feature(block)
        for block in feature_blocks(args.source.read_text())
    ]
    if args.expected_count is not None and len(features) != args.expected_count:
        raise SystemExit(
            f"feature count changed: expected {args.expected_count}, "
            f"found {len(features)}"
        )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(features, args.source))
    print(f"generated {len(features)} features -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
