// Generated by scripts/generate_experimental_feature_catalog.py.
// Source: /Users/example/projects/Codex-持续更新逆向Ipad版/artifacts/full-reverse-26.814.41957/official-codex-source/codex-rs/features/src/lib.rs
// Do not edit this file by hand.

extension CodexExperimentalFeatureSpec {
    public static let releasedCatalog: [Self] = [
        .init(
            name: "undo",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "shell_tool",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "view_image",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "secret_auth_storage",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "unified_exec",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "shell_zsh_fork",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "unified_exec_zsh_fork",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "shell_snapshot",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "deferred_executor",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "js_repl",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "executed_tool_call_metadata",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "code_mode",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "code_mode_buffered_exec",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "code_mode_host",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "code_mode_interrupt",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "code_mode_only",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "js_repl_tools_only",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "terminal_resize_reflow",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "web_search_request",
            stage: .deprecated,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "web_search_cached",
            stage: .deprecated,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "standalone_web_search",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "search_tool",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "codex_git_commit",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "runtime_metrics",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "sqlite",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "memories",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "external_agent_memory_import",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "local_thread_store_compression",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "background_paginated_rollout_migration",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "chronicle",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "apply_patch_freeform",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "apply_patch_streaming_events",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "apply_patch_preserve_line_endings",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "exec_permission_approvals",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "hooks",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "request_permissions_tool",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "use_linux_sandbox_bwrap",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "use_legacy_landlock",
            stage: .deprecated,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "request_rule",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "experimental_windows_sandbox",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "elevated_windows_sandbox",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "remote_models",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "enable_request_compression",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "network_proxy",
            stage: .beta,
            displayName: "Network proxy",
            description: "Apply network proxy restrictions to sandboxed sessions that already have network access.",
            announcement: "NEW: Network proxy can now be enabled from /experimental. Restart Codex after enabling it.",
            defaultEnabled: false
        ),
        .init(
            name: "respect_system_proxy",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "multi_agent",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "multi_agent_v2",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "multi_agent_mode",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "enable_fanout",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "apps",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "psp",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "enable_mcp_apps",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "mcp_2026_07_28",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "apps_mcp_path_override",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "tool_search",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "tool_search_always_defer_mcp_tools",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "deferred_tool_world_state",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "non_prefixed_mcp_tool_names",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "unavailable_dummy_tools",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "tool_suggest",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "recommended_plugins",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "plugins",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "executor_capability_discovery",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "plugin_hooks",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "in_app_browser",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "in_app_updates",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "browser_use",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "browser_use_full_cdp_access",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "browser_use_external",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "computer_use",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "remote_plugin",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "plugin_sharing",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "external_migration",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "image_generation",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "image_resize_notice",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "unified_image_budget",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "resize_all_images",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "item_ids",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "concurrent_reasoning_summaries",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "skill_mcp_dependency_install",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "skill_search",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "skill_env_var_dependency_prompt",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "mentions_v2",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "steer",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "default_mode_request_user_input",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "terminal_visualization_instructions",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "guardian_approval",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "guardian_reuse_parent_compaction",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "guardian_enhanced_node_repl_transcripts",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "guardian_node_repl_transcript_images",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "guardianv2",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "goals",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "token_budget",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "rollout_budget",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "current_time_reminder",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "collaboration_modes",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "tool_call_mcp_elicitation",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "auth_elicitation",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "personality",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "artifact",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "fast_mode",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "realtime_conversation",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "remote_control",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "image_detail_original",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "tui_app_server",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "prevent_idle_sleep",
            stage: .beta,
            displayName: "Prevent sleep while running",
            description: "Keep your computer awake while Codex is running a thread.",
            announcement: "NEW: Prevent sleep while running is now available in /experimental.",
            defaultEnabled: false
        ),
        .init(
            name: "workspace_owner_usage_nudge",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "responses_websockets",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "responses_websockets_v2",
            stage: .removed,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "remote_compaction_v2",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
        .init(
            name: "retain_client_developer_messages",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "use_agent_identity",
            stage: .underDevelopment,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: false
        ),
        .init(
            name: "workspace_dependencies",
            stage: .stable,
            displayName: nil,
            description: nil,
            announcement: nil,
            defaultEnabled: true
        ),
    ]
}
